document.writeln("<!--Alist V3建议添加的，已经默认添加了，如果你的没有建议加上-->");
document.writeln("<script src=\"https://polyfill.alicdn.com/v3/polyfill.min.js?features=String.prototype.replaceAll\"></script>");
document.writeln("");
document.writeln("<!--引入字体，全局字体使用-->");
document.writeln("<link rel=\"stylesheet\" href=\"https://npm.elemecdn.com/lxgw-wenkai-webfont@1.1.0/lxgwwenkai-regular.css\" />");
document.writeln("");
document.writeln("<!--评论系统使用的js-->");
document.writeln("<script src=\"https://unpkg.com/valine/dist/Valine.min.js\"></script>");
document.writeln("");
document.writeln("<!--不蒜子计数器-->");
document.writeln("<script async src=\"https://busuanzi.9420.ltd/js\"></script>");
document.writeln("");
document.writeln("<!-- Font6，自定义底部使用和看板娘使用的图标和字体文件-->");
document.writeln("<link type=\"text/css\" rel=\"stylesheet\" href=\"https://npm.elemecdn.com/font6pro@6.3.0/css/fontawesome.min.css\" media=\"all\" />");
document.writeln("<link href=\"https://npm.elemecdn.com/font6pro@6.3.0/css/all.min.css\" rel=\"stylesheet\" />");
document.writeln("");
document.writeln("<!--音乐播放器所用的文件-->");
document.writeln("<!-- require APlayer -->");
document.writeln("<link rel=\"stylesheet\" href=\"https://npm.elemecdn.com/aplayer@1.10.1/dist/APlayer.min.css\" />");
document.writeln("<script src=\"https://npm.elemecdn.com/aplayer@1.10.1/dist/APlayer.min.js\"></script>");
document.writeln("<!-- require MetingJS -->");
document.writeln("<script src=\"https://npm.elemecdn.com/meting2@0.0.1/js/Meting.min.js\"></script>");
document.writeln("");
document.writeln("<style>");
document.writeln("/* 去除通知栏 右上角 X */");
document.writeln(".notify-render .hope-close-button {");
document.writeln("display: none;");
document.writeln("}");
document.writeln("/*去掉底部*/");
document.writeln(".footer {");
document.writeln("display: none !important;");
document.writeln("}");
document.writeln("");
document.writeln("/* 此选项两处CSS 在v3.31.0中已优化 滚动显示 和 右下角设置网格模式尺寸大小 */");
document.writeln("/* 文字超长自动换行 */");
document.writeln("/*.name-box .name {");
document.writeln("white-space: unset !important;");
document.writeln("overflow: unset !important;");
document.writeln("}*/");
document.writeln("/* 缩略图图片变大 代码中的160px 自己改 现在是注释状态若需要自行解除注释 */");
document.writeln("/*.obj-box > div {");
document.writeln("grid-template-columns: repeat(auto-fill, minmax(160px, 1fr))");
document.writeln("}");
document.writeln(".obj-box > div .item-thumbnail{");
document.writeln("height: 100px;");
document.writeln("}*/");
document.writeln("");
document.writeln("/*");
document.writeln("图片API用法点进去都会有食用说明的,API来自网络不保证实效性稳定性自己测试");
document.writeln("樱花：https://www.dmoe.cc");
document.writeln("夏沫：https://cdn.seovx.com");
document.writeln("搏天：https://api.btstu.cn/doc/sjbz.php");
document.writeln("姬长信：https://github.com/insoxin/API");
document.writeln("小歪：https://api.ixiaowai.cn/");
document.writeln("保罗：https://api.paugram.com");
document.writeln("墨天逸：https://api.mtyqx.cn");
document.writeln("岁月小筑：https://img.xjh.me");
document.writeln("东方Project：https://img.paulzzh.com");
document.writeln("*/");
document.writeln("/*白天背景图*/");
document.writeln(".hope-ui-light {");
document.writeln("background-image: url(\"https://huannago.com/img/hennnachoco_natsu.jpg\") !important;");
document.writeln("background-repeat: no-repeat;");
document.writeln("background-size: cover;");
document.writeln("background-attachment: fixed;");
document.writeln("background-position-x: center;");
document.writeln("}");
document.writeln("/*夜间背景图*/");
document.writeln(".hope-ui-dark {");
document.writeln("background-image: url(\"https://huannago.com/img/yoru.jpg\") !important;");
document.writeln("background-repeat: no-repeat;");
document.writeln("background-size: cover;");
document.writeln("background-attachment: fixed;");
document.writeln("background-position-x: center;");
document.writeln("}");
document.writeln("");
document.writeln("/*主列表白天模式透明*/");
document.writeln(".obj-box.hope-stack.hope-c-dhzjXW.hope-c-PJLV.hope-c-PJLV-igScBhH-css {");
document.writeln("background-color: rgba(255, 255, 255, 0.5) !important;");
document.writeln("}");
document.writeln("/*主列表夜间模式透明*/");
document.writeln(".obj-box.hope-stack.hope-c-dhzjXW.hope-c-PJLV.hope-c-PJLV-iigjoxS-css {");
document.writeln("background-color: rgb(0 0 0 / 50%) !important;");
document.writeln("}");
document.writeln("/*readme白天模式透明*/");
document.writeln(".hope-c-PJLV.hope-c-PJLV-ikSuVsl-css {");
document.writeln("background-color: rgba(255, 255, 255, 0.5) !important;");
document.writeln("}");
document.writeln("/*readme夜间模式透明*/");
document.writeln(".hope-c-PJLV.hope-c-PJLV-iiuDLME-css {");
document.writeln("background-color: rgb(0 0 0 / 50%) !important;");
document.writeln("}");
document.writeln("");
document.writeln("");
document.writeln("/*顶部右上角切换按钮透明*/");
document.writeln(".hope-ui-light .hope-c-ivMHWx-hZistB-cv.hope-icon-button {");
document.writeln("background-color: rgba(255, 255, 255, 0.5) !important;");
document.writeln("}");
document.writeln(".hope-ui-dark .hope-c-ivMHWx-hZistB-cv.hope-icon-button {");
document.writeln("background-color: rgb(0 0 0 / 50%) !important;");
document.writeln("}");
document.writeln("");
document.writeln("");
document.writeln("/*右下角侧边栏按钮透明 第一个是白天 第二个是夜间*/");
document.writeln(".hope-ui-light .hope-c-PJLV-ijgzmFG-css {");
document.writeln("background-color: rgba(255, 255, 255, 0.5) !important;");
document.writeln("}");
document.writeln(".hope-ui-dark .hope-c-PJLV-ijgzmFG-css {");
document.writeln("background-color: rgb(0 0 0 / 50%) !important;");
document.writeln("}");
document.writeln("/*白天模式代码块透明*/");
document.writeln(".hope-ui-light pre {");
document.writeln("background-color: rgba(255, 255, 255, 0.1) !important;");
document.writeln("}");
document.writeln("/*夜间模式代码块透明*/");
document.writeln(".hope-ui-dark pre {");
document.writeln("background-color: rgba(255, 255, 255, 0) !important;");
document.writeln("}");
document.writeln("");
document.writeln("");
document.writeln("/*左侧侧边栏目录*/");
document.writeln("/*白天模式*/");
document.writeln(".hope-ui-light .hope-c-PJLV-ieGWMbI-css {");
document.writeln("background: rgba(255, 255, 255, 0.5) !important;");
document.writeln("}");
document.writeln("/*夜间模式*/");
document.writeln(".hope-ui-dark .hope-c-PJLV-ieGWMbI-css {");
document.writeln("background-color: rgb(0 0 0 / 50%) !important;");
document.writeln("}");
document.writeln("/* 返回顶部 */");
document.writeln(".hope-c-PJLV-ihVEsOa-css {");
document.writeln("background: rgba(255, 255, 255, 0.5) !important;");
document.writeln("}");
document.writeln(".hope-ui-dark .hope-c-PJLV-ihVEsOa-css {");
document.writeln("background-color: rgb(0 0 0 / 50%) !important;");
document.writeln("}");
document.writeln("");
document.writeln("");
document.writeln("/*顶部*/");
document.writeln("#root > .header {");
document.writeln("background: rgba(255, 255, 255, 0);");
document.writeln("}");
document.writeln("/*导航条*/");
document.writeln("/*白天模式*/");
document.writeln(".hope-ui-light .body > .nav {");
document.writeln("background-color: rgba(255, 255, 255, 0.5);");
document.writeln("border-radius: var(--hope-radii-xl);");
document.writeln("}");
document.writeln("/*夜间模式*/");
document.writeln(".hope-ui-dark .body > .nav {");
document.writeln("background-color: rgb(0 0 0 / 50%);");
document.writeln("border-radius: var(--hope-radii-xl);");
document.writeln("}");
document.writeln("/*隐藏导航条遮罩*/");
document.writeln(".body > .nav::after {");
document.writeln("display: none;");
document.writeln("}");
document.writeln("");
document.writeln("");
document.writeln("/*底部CSS，.App .table这三个一起的*/");
document.writeln("dibu {");
document.writeln("border-top: 0px;");
document.writeln("position: absolute;");
document.writeln("bottom: 0;");
document.writeln("width: 100%;");
document.writeln("margin: 0px;");
document.writeln("padding: 0px;");
document.writeln("}");
document.writeln(".App {");
document.writeln("min-height: 85vh;");
document.writeln("}");
document.writeln(".table {");
document.writeln("margin: auto;");
document.writeln("}");
document.writeln("");
document.writeln("");
document.writeln("/*全局字体*/");
document.writeln("* {");
document.writeln("font-family: LXGW WenKai;");
document.writeln("}");
document.writeln("* {");
document.writeln("font-weight: bold;");
document.writeln("}");
document.writeln("body {");
document.writeln("font-family: LXGW WenKai;");
document.writeln("}");
document.writeln("");
document.writeln("/*以下为评论系统专用*/");
document.writeln("/*适配大小契合度*/");
document.writeln(".newValine {");
document.writeln("width: min(96%, 940px);");
document.writeln("flex-direction: column;");
document.writeln("row-gap: var(--hope-space-2);");
document.writeln("border-radius: var(--hope-radii-xl);");
document.writeln("padding: var(--hope-space-2);");
document.writeln("box-shadow: var(--hope-shadows-lg);");
document.writeln("}");
document.writeln("/*评论区 - 白天模式透明度*/");
document.writeln(".hope-ui-light .newValine {");
document.writeln("background-color: rgba(255, 255, 255, 0.5) !important;");
document.writeln("}");
document.writeln("/*评论区 - 夜间模式透明度*/");
document.writeln(".hope-ui-dark .newValine {");
document.writeln("background-color: rgb(0 0 0 / 50%) !important;");
document.writeln("}");
document.writeln("/*输入栏里面跳舞的小人背景图,jsdelivr加载慢的可以自己替换或者删掉*/");
document.writeln(".vedit {");
document.writeln("background-image: url(\"https://cdn.jsdelivr.net/gh/anwen-anyi/imgAnwen/images/OuNiJiang.gif\");");
document.writeln("background-size: contain;");
document.writeln("background-repeat: no-repeat;");
document.writeln("background-position: right bottom;");
document.writeln("transition: all 0.25s ease-in-out 0s;");
document.writeln("}");
document.writeln("textarea#comment-textarea:focus {");
document.writeln("background-position-y: 120px;");
document.writeln("transition: all 0.25s ease-in-out 0s;");
document.writeln("}");
document.writeln("");
document.writeln("");
document.writeln("/*渐变背景CSS*/");
document.writeln("#canvas-basic {");
document.writeln("position: fixed;");
document.writeln("display: block;");
document.writeln("width: 100%;");
document.writeln("height: 100%;");
document.writeln("top: 0;");
document.writeln("right: 0;");
document.writeln("bottom: 0;");
document.writeln("left: 0;");
document.writeln("z-index: -999;");
document.writeln("}");
document.writeln("");
document.writeln("");
document.writeln("/* 以下为音乐播放器额外配置 */");
document.writeln("/* 如果你想要音乐播放器不是很靠底部可以自己设置一下数值 0是靠最底部 */");
document.writeln(".aplayer .aplayer-body,");
document.writeln(".aplayer.aplayer-withlist {");
document.writeln("bottom: 0rem !important;");
document.writeln("}");
document.writeln("/*音乐播放器进一步进行隐藏*/");
document.writeln("/* 需要就加不需要就不用加 */");
document.writeln(".aplayer.aplayer-fixed.aplayer-narrow .aplayer-body {");
document.writeln("left: -66px !important;");
document.writeln("}");
document.writeln(".aplayer.aplayer-fixed.aplayer-narrow .aplayer-body:hover {");
document.writeln("left: 0 !important;");
document.writeln("}");
document.writeln("</style>");