document.writeln("<!--Alist V3建议添加的，已经默认添加了，如果你的没有建议加上-->");
document.writeln("<script src=\"https://polyfill.alicdn.com/v3/polyfill.min.js?features=String.prototype.replaceAll\"></script>");
document.writeln("");
document.writeln("<!--引入字体，全局字体使用-->");
document.writeln("<!--link rel=\"stylesheet\" href=\"./alist_font.css\" /-->");
document.writeln("");
document.writeln("<!--评论系统使用的js-->");
document.writeln("<script src=\"https://unpkg.com/valine/dist/Valine.min.js\"></script>");
document.writeln("");
document.writeln("<!--不蒜子计数器-->");
document.writeln("<script async src=\"https://busuanzi.9420.ltd/js\"></script>");
document.writeln("");
document.writeln("<!-- Font6，自定义底部使用和看板娘使用的图标和字体文件-->");
document.writeln("<link type=\"text/css\" rel=\"stylesheet\" href=\"https://npm.elemecdn.com/font6pro@6.3.0/css/fontawesome.min.css\" media=\"all\" />");
document.writeln("<link href=\"https://npm.elemecdn.com/font6pro@6.3.0/css/all.min.css\" rel=\"stylesheet\" />");
document.writeln("");
document.writeln("<!--音乐播放器所用的文件-->");
document.writeln("<!-- require APlayer -->");
document.writeln("<link rel=\"stylesheet\" href=\"https://npm.elemecdn.com/aplayer@1.10.1/dist/APlayer.min.css\" />");
document.writeln("<script src=\"https://npm.elemecdn.com/aplayer@1.10.1/dist/APlayer.min.js\"></script>");
document.writeln("<!-- require MetingJS -->");
document.writeln("<script src=\"https://npm.elemecdn.com/meting2@0.0.1/js/Meting.min.js\"></script>");